#!/bin/bash
set -e
POSTGRES_USER=postgres
POSTGRES_DB=pricingdb

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER rodzers WITH PASSWORD 'rodzerspassword';
    CREATE USER dominik WITH PASSWORD 'dominikpassword';
    REVOKE ALL ON DATABASE postgres FROM public;
    REVOKE ALL ON DATABASE pricingdb FROM public;
    REVOKE ALL ON DATABASE postgres FROM public;
    REVOKE ALL ON DATABASE template0 FROM public;
    REVOKE ALL ON DATABASE template1 FROM public;
    GRANT ALL PRIVILEGES ON DATABASE pricingdb TO rodzers;
    GRANT ALL PRIVILEGES ON DATABASE pricingdb TO dominik;
    GRANT USAGE, SELECT, INSERT, UPDATE, DELETE, CREATE ON ALL TABLES IN SCHEMA public TO rodzers;
    GRANT USAGE, SELECT, INSERT, UPDATE, DELETE, CREATE ON ALL TABLES IN SCHEMA public TO dominik;
    GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO rodzers;
  GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO dominik;
EOSQL
