spring:
  datasource:
    url: jdbc:postgresql://34.76.173.46:5432/pricingdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres_password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: pricespy19052023@outlook.com
    password: price_spy_secure_password_123
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  profiles:
    active:
      - cloud
server:
  port: 8080

logging:
  level:
    root: debug