# Postgres - Database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pricingdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgrespassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
server:
  port: 8080

# H2 - Database
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
#        format_sql: true
#server:
#  port: 8080
