
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pricingdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgrespassword
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  profiles:
      active:
        - seed-data
server:
  port: 8080

logging:
  level:
    root: debug

